### ISSUE TITLE
could not find package epub_parser

### ISSUE THREAD

**Issue by Himani75** [foureyez/ebreader#1]
Because ebook_reader depends on epub_parser from path which doesn't exist (could not find package epub_parser at "../epub-parser"), version solving failed.
pub get failed (66; Because ebook_reader depends on epub_parser from path which doesn't exist (could not find package epub_parser at "../epub-parser"), version solving failed.)
Process

**Comment by foureyez** [comment]
Hi,
I've commented out the code in pubspec.yaml which picks the epub-parser directly from GitHub instead of local disk for debugging purposes.
I'll uncomment it, for now you can locally make this change and it should work fine.
